[[redirects]]
  from = "/api/*"
  to = "https://dev.teammanagers.kr/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BASE_URL = "From netlify.toml VITE_BASE_URL"
  REACT_APP_API_TOKEN = "From netlify.toml VITE_API_TOKEN"